title: TAMEKA CHI SMALL
author: Tameka Small
email: tamekasmall@ymail.com
description: > # this means to ignore newlines until "baseurl:"
  My journey from as a software developer. Coding yogi. 

# social links
twitter_username: @tamekasmall
github_username:  @tamekasmall
instagram_username: @tamekasmall

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
